# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20170707_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('Learning', (('Python', 'python'), ('Java', 'java'))), ('Life', 'life')], max_length=20),
        ),
    ]
