# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20170707_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('Learning', (('Python', 'python'), ('Java', 'java'))), ('Life', 'life'), ('Other', 'other')], max_length=20),
        ),
    ]
