# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20170707_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='markdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('content', django_markdown.models.MarkdownField()),
            ],
        ),
    ]
