# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20170707_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.TextField(blank=True),
        ),
    ]
