# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20170707_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='content',
        ),
    ]
