# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20170707_0312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='markdown',
        ),
    ]
