# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_delete_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
