# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 05:08
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20170707_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
