# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20170707_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='view_time',
            field=models.IntegerField(default=1),
        ),
    ]
