# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(null=True, blank=True),
        ),
    ]
