# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='auto_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
