# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 01:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_auto_20170728_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='auto_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 28, 1, 31, 46, 632627, tzinfo=utc)),
        ),
    ]
