# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0024_auto_20170728_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='auto_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 28, 1, 42, 6, 162652, tzinfo=utc)),
        ),
    ]
