# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0025_auto_20170728_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auto_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
