# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0028_remove_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='auto_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
