# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0031_auto_20170728_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_status',
            field=models.BooleanField(default=False),
        ),
    ]
