# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0032_article_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
