# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-18 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0035_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
