# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-18 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0036_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_myself',
            field=models.BooleanField(default=False),
        ),
    ]
