# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0038_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
    ]
