# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-16 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0039_comment_has_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar_color',
            field=models.CharField(choices=[('#4B515E', 'black'), ('#ACB8B8', 'gray'), ('#F2C42C', 'yellow'), ('#EA9752', 'orange'), ('#E84C3D', 'red')], max_length=20, null=True),
        ),
    ]
