# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-17 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0040_comment_avatar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar_color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
